version: '3.7'

services:
  animal-crossing-market:
    build:
      context: .
    image: animal-crossing-market
    init: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      # - minio
    env_file:
      - .env
    command: >
      sh -c "bundle install && bundle exec rails s"
  db:
    image: postgres:11.1-alpine

  redis:
    image: redis:5.0.9
