enqueue_active_listings_job:
  cron: "* * * * *"
  class: "EnqueueActiveListingsJob"
  queue: default

auto_complete_join_listings_job:
  cron: "* * * * *"
  class: "AutoCompleteJoinListingsJob"
  queue: default